# Generated by Django 5.2.16 on 2026-08-02 06:26

import apps.core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRateSnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('class_grade_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'class_grade_id', 'term_id'), name='attendanceratesnapshot_unique_per_class_term')],
            },
        ),
        migrations.CreateModel(
            name='FeeCollectionSnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('class_grade_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collection_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'class_grade_id', 'term_id'), name='feecollectionsnapshot_unique_per_class_term')],
            },
        ),
        migrations.CreateModel(
            name='MeanGradeRollup',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('class_grade_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('mean_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mean_grade', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'class_grade_id', 'term_id'), name='meangraderollup_unique_per_class_term')],
            },
        ),
    ]
