# Generated by Django 5.2.16 on 2026-07-27 13:30

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('curriculum_type', models.CharField(choices=[('cbc', 'CBC'), ('844', '8-4-4'), ('british', 'British'), ('tvet', 'TVET'), ('university', 'University')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('year_label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'year_label'), name='academicyear_unique_label_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='classes_streams.classgrade')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='classes_streams.academicyear')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('staff_id', models.UUIDField()),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes_streams.classgrade')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes_streams.stream')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='classes_streams.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classgrade',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_grades', to='classes_streams.term'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('class_grade', 'name'), name='stream_unique_name_per_class'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='term_unique_name_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('institution_id',), name='term_one_current_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='classteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', True)), fields=('class_grade', 'term'), name='classteacher_unique_per_class_when_no_stream'),
        ),
        migrations.AddConstraint(
            model_name='classteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', False)), fields=('class_grade', 'stream', 'term'), name='classteacher_unique_per_stream'),
        ),
        migrations.AddConstraint(
            model_name='classgrade',
            constraint=models.UniqueConstraint(fields=('term', 'name', 'curriculum_type'), name='classgrade_unique_per_term'),
        ),
        migrations.AddConstraint(
            model_name='classgrade',
            constraint=models.CheckConstraint(condition=models.Q(('curriculum_type__in', ['cbc', '844', 'british', 'tvet', 'university'])), name='classgrade_valid_curriculum_type'),
        ),
    ]
