# Generated by Django 5.2.16 on 2026-07-29 09:33

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'name'), name='corevalue_unique_name_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('subject_catalog_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'code'), name='learningarea_unique_code_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('strand', models.CharField(max_length=100)),
                ('sub_strand', models.CharField(blank=True, max_length=100)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='curriculum_cbc.learningarea')),
            ],
            options={
                'ordering': ['strand', 'sub_strand'],
            },
        ),
        migrations.CreateModel(
            name='PCI',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'PCI',
                'verbose_name_plural': 'PCIs',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'name'), name='pci_unique_name_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('description', models.TextField(blank=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='curriculum_cbc.competency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContinuousAssessment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('performance_level', models.CharField(choices=[('exceeding_expectation', 'Exceeding Expectation'), ('meeting_expectation', 'Meeting Expectation'), ('approaching_expectation', 'Approaching Expectation'), ('below_expectation', 'Below Expectation')], max_length=30)),
                ('evidence_notes', models.TextField(blank=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuous_assessments', to='curriculum_cbc.competency')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'student_id', 'competency', 'term_id'), name='continuousassessment_unique_per_student_competency_term'), models.CheckConstraint(condition=models.Q(('performance_level__in', ['exceeding_expectation', 'meeting_expectation', 'approaching_expectation', 'below_expectation'])), name='continuousassessment_valid_performance_level')],
            },
        ),
    ]
