# Generated by Django 5.2.16 on 2026-07-30 06:44

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('supervisor_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='proposed', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('programme_code', models.CharField(max_length=20)),
                ('degree_level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD')], max_length=20)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'name'), name='faculty_unique_name_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='curriculum_university.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('term_id', models.UUIDField()),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'term_id'), name='semester_unique_term_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='GPASnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_snapshots', to='curriculum_university.semester')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('unit_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('semester_offered', models.PositiveSmallIntegerField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='curriculum_university.programme')),
            ],
            options={
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='curriculum_university.semester')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='curriculum_university.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitAssessment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('assessment_type', models.CharField(choices=[('assignment', 'Assignment'), ('cat', 'CAT'), ('final_exam', 'Final Exam')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='curriculum_university.semester')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='curriculum_university.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityDepartment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='curriculum_university.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='curriculum_university.universitydepartment'),
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('conferred_at', models.DateTimeField()),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='curriculum_university.programme')),
            ],
            options={
                'ordering': ['-conferred_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'student_id', 'programme'), name='graduation_unique_per_student_programme')],
            },
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('institution_id', 'faculty', 'name'), name='school_unique_name_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='gpasnapshot',
            constraint=models.UniqueConstraint(fields=('institution_id', 'student_id', 'semester'), name='gpasnapshot_unique_per_student_semester'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('institution_id', 'unit_code'), name='unit_unique_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(fields=('institution_id', 'student_id', 'unit', 'semester'), name='courseregistration_unique_per_student_unit_semester'),
        ),
        migrations.AddConstraint(
            model_name='unitassessment',
            constraint=models.UniqueConstraint(fields=('institution_id', 'student_id', 'unit', 'semester', 'assessment_type'), name='unitassessment_unique_per_student_unit_semester_type'),
        ),
        migrations.AddConstraint(
            model_name='unitassessment',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='unitassessment_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='unitassessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='unitassessment_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='unitassessment',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', models.F('max_score'))), name='unitassessment_score_within_max'),
        ),
        migrations.AddConstraint(
            model_name='universitydepartment',
            constraint=models.UniqueConstraint(fields=('institution_id', 'school', 'name'), name='universitydepartment_unique_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('institution_id', 'programme_code'), name='programme_unique_code_per_institution'),
        ),
    ]
