# Generated by Django 5.2.16 on 2026-07-28 09:34

import apps.core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user_id', models.UUIDField()),
                ('employee_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'employee_number'), name='staffprofile_unique_employee_number_per_institution'), models.UniqueConstraint(fields=('institution_id', 'user_id'), name='staffprofile_unique_user_per_institution')],
            },
        ),
    ]
