# Generated by Django 5.2.16 on 2026-07-29 07:47

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('term_id', models.UUIDField()),
                ('class_grade_id', models.UUIDField()),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'term_id', 'class_grade_id'), name='timetable_unique_per_term_class')],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSlotAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('subject_id', models.UUIDField()),
                ('staff_id', models.UUIDField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_slot_assignments', to='timetable.period')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('period',), name='subjectslotassignment_one_per_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('timetable', 'day_of_week', 'start_time'), name='period_unique_start_per_timetable_day'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='period_start_before_end'),
        ),
    ]
