# Generated by Django 5.2.16 on 2026-08-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='acting_as_admin',
            field=models.BooleanField(default=False),
        ),
    ]
