# Generated by Django 5.2.16 on 2026-07-30 11:17

import apps.core.uuid7
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('class_grade_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('line_items', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'class_grade_id', 'term_id', 'name'), name='feestructure_unique_per_class_term_name')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('fee_structure_id', models.UUIDField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution_id', 'term_id'], name='finance_inv_institu_4b4df2_idx'), models.Index(fields=['institution_id', 'student_id'], name='finance_inv_institu_5358db_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['unpaid', 'partial', 'paid', 'overdue', 'cancelled'])), name='invoice_valid_status'), models.CheckConstraint(condition=models.Q(('amount_due__gte', 0)), name='invoice_amount_due_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('num_installments', models.PositiveSmallIntegerField()),
                ('schedule', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='finance.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank')], max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('recorded_by_id', models.UUIDField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('receipt_number', models.CharField(max_length=30)),
                ('pdf_document', models.CharField(blank=True, default='', max_length=255)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('amount_or_percent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_percent', models.BooleanField(default=False)),
                ('funded_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_or_percent__gt', 0)), name='scholarship_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution_id', 'invoice'], name='finance_pay_institu_aa7e14_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('institution_id', 'receipt_number'), name='receipt_unique_number_per_institution'),
        ),
    ]
