# Generated by Django 5.2.16 on 2026-07-30 12:43

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSTKPushRequest',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=50)),
                ('checkout_request_id', models.CharField(blank=True, default='', max_length=50)),
                ('verification_token', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, default='', max_length=255)),
                ('initiated_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_transaction_id__isnull', False)), fields=('institution_id', 'mpesa_transaction_id'), name='payment_unique_mpesa_transaction_id'),
        ),
        migrations.AddField(
            model_name='mpesastkpushrequest',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='mpesastkpushrequest',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_stk_request', to='finance.payment'),
        ),
        migrations.AddIndex(
            model_name='mpesastkpushrequest',
            index=models.Index(fields=['institution_id', 'checkout_request_id'], name='finance_mpe_institu_e83877_idx'),
        ),
        migrations.AddConstraint(
            model_name='mpesastkpushrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='mpesastkpush_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='mpesastkpushrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'success', 'failed', 'cancelled'])), name='mpesastkpush_valid_status'),
        ),
    ]
