# Generated by Django 5.2.16 on 2026-07-30 15:43

import apps.core.uuid7
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_mpesastkpushrequest_payment_mpesa_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incurred_at', models.DateField()),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-incurred_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expenserecord_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('staff_id', models.UUIDField()),
                ('period', models.DateField()),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'staff_id', 'period'), name='payroll_unique_per_staff_period'), models.CheckConstraint(condition=models.Q(('gross__gt', 0)), name='payroll_gross_positive')],
            },
        ),
    ]
