# Generated by Django 5.2.16 on 2026-07-29 14:32

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('subject_catalog_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('qualification_level', models.CharField(choices=[('none', 'None'), ('igcse', 'IGCSE'), ('a_level', 'A-Level')], default='none', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'code'), name='subjectbritish_unique_code_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('class_grade_id', models.UUIDField()),
                ('key_stage', models.CharField(choices=[('eyfs', 'EYFS'), ('ks1', 'Key Stage 1'), ('ks2', 'Key Stage 2'), ('ks3', 'Key Stage 3'), ('ks4', 'Key Stage 4'), ('ks5', 'Key Stage 5')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'class_grade_id'), name='yeargroup_unique_class_grade_per_institution'), models.CheckConstraint(condition=models.Q(('key_stage__in', ['eyfs', 'ks1', 'ks2', 'ks3', 'ks4', 'ks5'])), name='yeargroup_valid_key_stage')],
            },
        ),
        migrations.CreateModel(
            name='PredictedGrade',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('academic_year_id', models.UUIDField()),
                ('predicted_grade', models.CharField(max_length=10)),
                ('set_by', models.UUIDField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_grades', to='curriculum_british.subject')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'student_id', 'subject', 'academic_year_id'), name='predictedgrade_unique_per_student_subject_year')],
            },
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('component', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseworks', to='curriculum_british.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'student_id', 'subject', 'term_id', 'component'), name='coursework_unique_per_student_subject_term_component'), models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='coursework_score_non_negative'), models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='coursework_max_score_positive'), models.CheckConstraint(condition=models.Q(('score__lte', models.F('max_score'))), name='coursework_score_within_max')],
            },
        ),
    ]
