# Generated by Django 5.2.16 on 2026-07-28 10:04

import apps.core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField()),
                ('preferred_language', models.CharField(blank=True, default='en', max_length=10)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'user_id'), name='parentprofile_unique_user_per_institution')],
            },
        ),
    ]
