# Generated by Django 5.2.16 on 2026-07-30 06:00

import apps.core.uuid7
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('course_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyUnit',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('unit_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_units', to='curriculum_tvet.course')),
            ],
            options={
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_number', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='curriculum_tvet.course')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustrialAttachment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('host_organization', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('supervisor_report', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='industrialattachment_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='PracticalAssessment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('assessment_type', models.CharField(choices=[('workshop', 'Workshop Assessment'), ('practical_exam', 'Practical Exam')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessor_id', models.UUIDField()),
                ('competency_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_assessments', to='curriculum_tvet.competencyunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TVETDepartment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'name'), name='tvetdepartment_unique_name_per_institution')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curriculum_tvet.tvetdepartment'),
        ),
        migrations.AddConstraint(
            model_name='competencyunit',
            constraint=models.UniqueConstraint(fields=('institution_id', 'course', 'unit_code'), name='competencyunit_unique_code_per_course'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('institution_id', 'certificate_number'), name='certificate_unique_number_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='practicalassessment',
            constraint=models.UniqueConstraint(fields=('institution_id', 'student_id', 'competency_unit', 'term_id', 'assessment_type'), name='practicalassessment_unique_per_student_unit_term_type'),
        ),
        migrations.AddConstraint(
            model_name='practicalassessment',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='practicalassessment_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='practicalassessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='practicalassessment_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='practicalassessment',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', models.F('max_score'))), name='practicalassessment_score_within_max'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('institution_id', 'course_code'), name='course_unique_code_per_institution'),
        ),
    ]
