# Generated by Django 5.2.16 on 2026-07-28 10:16

import apps.core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('curriculum_type', models.CharField(choices=[('cbc', 'CBC'), ('844', '8-4-4'), ('british', 'British'), ('tvet', 'TVET'), ('university', 'University')], max_length=20)),
                ('levels', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['curriculum_type'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'curriculum_type'), name='gradingscale_unique_per_institution_curriculum'), models.CheckConstraint(condition=models.Q(('curriculum_type__in', ['cbc', '844', 'british', 'tvet', 'university'])), name='gradingscale_valid_curriculum_type')],
            },
        ),
        migrations.CreateModel(
            name='SubjectCatalog',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('curriculum_type', models.CharField(choices=[('cbc', 'CBC'), ('844', '8-4-4'), ('british', 'British'), ('tvet', 'TVET'), ('university', 'University')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'curriculum_type', 'code'), name='subjectcatalog_unique_code_per_institution_curriculum'), models.CheckConstraint(condition=models.Q(('curriculum_type__in', ['cbc', '844', 'british', 'tvet', 'university'])), name='subjectcatalog_valid_curriculum_type')],
            },
        ),
    ]
