# Generated by Django 5.2.16 on 2026-08-02 04:30

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('visit_date', models.DateField()),
                ('treated_by_id', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('allergies', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'student_id'), name='healthrecord_one_per_student')],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clinic.clinicvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
