# Generated by Django 5.2.16 on 2026-07-16 06:32

import apps.core.uuid7
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('isolation_tier', models.CharField(choices=[('shared_row', 'Shared database, row isolation'), ('dedicated_db', 'Dedicated database, shared infrastructure'), ('dedicated_infra', 'Dedicated infrastructure')], default='shared_row', max_length=20)),
                ('db_alias', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('primary_color', models.CharField(blank=True, default='', max_length=20)),
                ('favicon_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('isolation_tier__in', ['shared_row', 'dedicated_db', 'dedicated_infra'])), name='institution_valid_isolation_tier'), models.CheckConstraint(condition=models.Q(models.Q(('isolation_tier', 'dedicated_db'), _negated=True), models.Q(('db_alias', ''), _negated=True), _connector='OR'), name='institution_dedicated_db_requires_db_alias')],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendarSettings',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year_start_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('terms_per_year', models.PositiveSmallIntegerField(default=3)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to='institutions.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom domain')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='institutions.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('institution',), name='one_primary_domain_per_institution'), models.CheckConstraint(condition=models.Q(('domain_type__in', ['subdomain', 'custom'])), name='domain_valid_type')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionCurriculum',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_type', models.CharField(choices=[('cbc', 'CBC'), ('844', '8-4-4'), ('british', 'British'), ('tvet', 'TVET'), ('university', 'University')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='institutions.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'curriculum_type'), name='unique_institution_curriculum'), models.CheckConstraint(condition=models.Q(('curriculum_type__in', ['cbc', '844', 'british', 'tvet', 'university'])), name='institution_curriculum_valid_type')],
            },
        ),
    ]
