# Generated by Django 5.2.16 on 2026-07-27 10:52

import apps.core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_address', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push')], max_length=10)),
                ('template_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='institutions.institution')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'created_at'], name='notificatio_institu_9cf7f0_idx'), models.Index(fields=['recipient_user', 'created_at'], name='notificatio_recipie_ff321e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('channel__in', ['sms', 'email', 'push'])), name='notiflog_valid_channel'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'sent', 'delivered', 'failed'])), name='notiflog_valid_status')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push')], max_length=10)),
                ('subject_template', models.TextField(blank=True, default='')),
                ('body_template', models.TextField()),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='institutions.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'key', 'channel'), name='notiftemplate_unique_per_institution'), models.UniqueConstraint(condition=models.Q(('institution__isnull', True)), fields=('key', 'channel'), name='notiftemplate_unique_platform_default'), models.CheckConstraint(condition=models.Q(('channel__in', ['sms', 'email', 'push'])), name='notiftemplate_valid_channel')],
            },
        ),
    ]
