# Generated by Django 5.2.16 on 2026-07-28 08:36

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('admission_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'admission_number'), name='student_unique_admission_number_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('guardian_user_id', models.UUIDField()),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('emergency_contact', 'Emergency contact'), ('other', 'Other')], max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to='students.student')),
            ],
            options={
                'ordering': ['-is_primary_contact'],
                'constraints': [models.UniqueConstraint(fields=('student', 'guardian_user_id'), name='guardianrelationship_unique_student_guardian')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('class_grade_id', models.UUIDField()),
                ('stream_id', models.UUIDField(blank=True, null=True)),
                ('term_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='active', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'term_id'), name='enrollment_unique_student_per_term'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'transferred', 'withdrawn', 'completed'])), name='enrollment_valid_status')],
            },
        ),
    ]
