# Generated by Django 5.2.16 on 2026-07-29 12:55

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeanGradeSnapshot',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('mean_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mean_grade', models.CharField(max_length=10)),
                ('rank_in_class', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_in_stream', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'student_id', 'term_id'), name='meangradesnapshot_unique_per_student_term')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('subject_catalog_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'code'), name='subject844_unique_code_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('exam_type', models.CharField(choices=[('cat', 'CAT'), ('midterm', 'Midterm'), ('end_term', 'End Term'), ('mock', 'Mock'), ('kcpe_kcse', 'KCPE/KCSE')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='curriculum_844.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'student_id', 'subject', 'term_id', 'exam_type'), name='examresult_unique_per_student_subject_term_type'), models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='examresult_score_non_negative'), models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='examresult_max_score_positive'), models.CheckConstraint(condition=models.Q(('score__lte', models.F('max_score'))), name='examresult_score_within_max'), models.CheckConstraint(condition=models.Q(('exam_type__in', ['cat', 'midterm', 'end_term', 'mock', 'kcpe_kcse'])), name='examresult_valid_exam_type')],
            },
        ),
    ]
