# Generated by Django 5.2.16 on 2026-08-02 05:51

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transport.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transport.stop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('make_model', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['registration_number'],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'registration_number'), name='vehicle_unique_registration_per_institution')],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='stop_unique_sequence_per_route'),
        ),
        migrations.AddConstraint(
            model_name='transportassignment',
            constraint=models.UniqueConstraint(fields=('institution_id', 'student_id'), name='transportassignment_one_per_student'),
        ),
    ]
